sources:
  - name: saas
    catalog: raw_data_saas
    schema: default
    tables:
      - name: accounts
      - name: opportunities
      - name: contacts
      - name: activities_with_dates
      ##adding a freshness block for dbt to throw warning or error if the data is nto fresh. needs a "loaded at field"
          loaded_at_field: date ##this will be the ETL Date. can be useful if it is a table that is changed frequently
          freshness:
            warn_after:
              count: 6
              period: hour
            error_after:
              count: 120
              period: day
      - name: products
      - name: quotes
      - name: quote_lines
      - name: users
      ##source freshness!!!
## lorenzo is the king and data wizard
