version: 2

sources:
  - name: saas
    catalog: raw_data_saas
    schema: default
    tables:
      - name: accounts
      - name: opportunities
      - name: contacts
      - name: activities_with_dates
      - name: products
      - name: quotes
      - name: quote_lines
      - name: users
## lorenzo is the king and data wizard